### ISSUE TITLE
Modulus web-side + Meteor Cordova =  :-(

### ISSUE THREAD

**Issue by benstr** [onmodulus/demeteorizer#105]
I have a couple Meteor web apps on Modulus. Now I want to deploy a Cordova app for one. My web app on Modulus ran through demeteorizer before getting deployed. But Meteor's `Cordova Build` does not demeteorize which results in a stalemate. Hot-code pushes work but no other functions work :(  How can I get these two great things working in harmony?

**Comment by kevohagan** [comment]
+1 on this

**Comment by benstr** [comment]
Actually Cordova Build is only for building the app-store app. After cordova build you can deploy the Meteor app like you normally would to Modulus (without cordova build). Everything works fine now :)
