### ISSUE TITLE
Extracting bundle failed, tar command failed

### ISSUE THREAD

**Issue by kristdev** [onmodulus/demeteorizer#106]
Hello, i'm new on meteor and i try to use demeteorizer to run my meteor project on node server, but i know a failure.
these are the messages:

    J:\meteorprojects\leaderboard>demeteorizer                            
    Input: J:\meteorprojects\leaderboard                                  
    Output: J:\meteorprojects\leaderboard\.demeteorized                   
    Creating output folder.                                               
    Bundling Meteor App...                                                
    meteor bundle generation complete.                                    
    Extracting bundle.                                                    
    ERROR: Error: Command failed: tar: Cannot connect to J: resolve failed

I've installed cygwin on my computer and aadded the the bin path on my path environnement. How cani i fixed the problem?
I would like to precise, i see the archive, and i can extract, the problem is , there is not package.json

**Comment by fiveisprime** [comment]
That looks like the output of an older version of demeteorizer. What
version of Meteor are you using? If you are *above* Meteor 0.8.1, you
can update to the latest demeteorize (v2.0.6) and that will fix your
issue.

If you are *at or below* Meteor 0.8.1, we'll need to find a way to get
the tar command working on Windows.

**Comment by kristdev** [comment]
i'm using meteor 0.8. That's the reason why i installed cygwin. Do you know other tool can make me to install tar command?

**Comment by fiveisprime** [comment]
Closing this now that Windows support is pretty solid. I'll reopen this if it's
still an issue, just let me know.
