### ISSUE TITLE
demeteorizer fails on nitrous

### ISSUE THREAD

**Issue by kristdev** [onmodulus/demeteorizer#109]
Hello, i'm testing nitrous for meteor project. All works fine, i install demeteorizer, but demeteorizer command doesn't work. Can you help me?

**Comment by fiveisprime** [comment]
What is the output from the command?

**Comment by kristdev** [comment]
action@meteordev2707-193311:~/workspace/examples/leaderboard$ demeteorizer
    Input:  /home/action/workspace/examples/leaderboard
    Output: /home/action/workspace/examples/leaderboard/.demeteorized
    Determining Meteor version...
    Meteor version: 1.0.3.1
    Output folder exists, deleting...
    Bundling Meteor App...
    Demeteorization failed: Command failed: This command has been deprecated in favor 
    of 'meteor build', which allows you
    to build for multiple platforms and outputs a directory instead of a single
    tarball. See 'meteor help build'for more information.


    WARNING: The output directory is under your source tree.

    Errors prevented bundling:
    While building the application:
    node_modules/demeteorizer/node_modules/semver/foot.js:8:1: Unexpected token }
    node_modules/demeteorizer/node_modules/semver/head.js:4:3: Unexpected end of
    input

**Comment by Kriegslustig** [comment]
Same problem here. I tried installing the latest version of semver which would be 4.3.3. But demeteorizer still loads 3.0.1.

**Comment by fiveisprime** [comment]
The semver dependency of 3.0.1 is correct, this is an issue with one of the
packages the application is using.

What else was added to the leaderboard example? Is this even still an issue?
