### ISSUE TITLE
idea: allow output overwrite for proper git use and git push deployments

### ISSUE THREAD

**Issue by BretFisher** [onmodulus/demeteorizer#11]
Many node deployment systems use git. The current demeteorizer requires a new output folder to be created on each use, preventing the ability to make the demeteorizer directority a git enabled location for tracking changes and pushing via git to deployment systems.

I get that meteor bundle and demeteorizer are usually meant to create temp (disposable) copies of meteor code, but what about the following idea:

### User Story: Workflow for Deploying to Azure, Pushing to github, etc.
* I have my app in /app. It's in source control like normal
* I have run `demeteorizer -o ../appDeploy` once
* Then add /appDeploy to source control and make first commit. I can then deploy to various source-control-enabled deployment systems.
* I then make changes in /app and want to redeploy the updates with demeteorizer using my existing appDeploy git repo. **Today this step won't work.**

### Additional Demeteorizer Functionality 
* add a demeteorizer option `-w --overwrite`
* It will then not delete the directory first, or complain about it's existence.
* It will somehow overwrite all files.
* I can then add another source control commit to /appDeploy and track it's changes, allowing another push to Azure, github, etc.

Note: I tried to add this functionality myself with tar, mv, cp, etc. I couldn't get it to work. Basically we need to "copy directories and all subfiles and directories to existing directory and silently overwrite all subfiles and directories". That's the only step I'm missing for this feature.

**Comment by vitch** [comment]
:+1: to this feature, I need to do a similar thing...

I guess you could remove everything except `.git` from the destination folder and then generate the demetorized version into it?

**Comment by talha-asad** [comment]
Maybe you could do it by just adding the demeteorized folder to your gitignore? and generate on where you deploy.

**Comment by sjmcdowall** [comment]
As of demeteorizer 3 (the latest) it now deploys to a "build" directory under the -o output path, so hopefully this won't be an issue anymore?
