### ISSUE TITLE
Fails with meteor-sharejs

### ISSUE THREAD

**Issue by DavidSichau** [onmodulus/demeteorizer#110]
I try to run demeteorizer on an app with the meteor  package meteor-sharejs. 

https://github.com/mizzao/meteor-sharejs

However there are some files missing in the end.

The folder 

      /programs/web.browser/packages/mizzao_sharejs/.npm/package

is empty after running `npm install`

However there needs to be the npm package `share` be installed.

What step did I miss?

For an try out you can use the demo app in the meteor-sharejs repo, there the same problem occures.

**Comment by brg2** [comment]
+1?

**Comment by fiveisprime** [comment]
Check out https://github.com/mizzao/meteor-sharejs/issues/37

We'll have to figure out a way to get the dependencies for meteor-sharejs
included in the bundle.
