### ISSUE TITLE
Question: Ignoring files & folders

### ISSUE THREAD

**Issue by boustanihani** [onmodulus/demeteorizer#112]
How could we ignore files & folders when using demeteorizer?

Is there something similar to **.modulusignore** ?
http://help.modulus.io/customer/portal/articles/1702010

**Comment by fiveisprime** [comment]
What problem are you trying to solve with the ability to ignore
files/directories?

**Comment by boustanihani** [comment]
Its been a long time, I forgot what the problem was :bowtie:

**Comment by fiveisprime** [comment]
Haha dang, alright. I'm going to close this, open a new issue if it comes up
again. :)
