### ISSUE TITLE
Error after 'Bundling Meteor App' message. Prints 'undefined'

### ISSUE THREAD

**Issue by i4han** [onmodulus/demeteorizer#115]
Message from: isaac@hi16.ca
UserId: 44260

Meteor deployment has errors.

$ modulus deploy
Welcome to Modulus
You are logged in as isaac@hi16.ca
[?] Are you sure you want to use project app? (yes) 
Meteor project detected...
Input: /Users/isaac/workspace/app
Output: /Users/isaac/workspace/app/.demeteorized
Determining Meteor version...
Meteor version: 1.0.4
Bundling Meteor App...
undefined
[Error] Error: Command failed: This command has been deprecated in favor of 'meteor build', which allows you
to build for multiple platforms and outputs a directory instead of a single
tarball. See 'meteor help build'for more information.

**Comment by fiveisprime** [comment]
The `undefined` in the output is where issue is. The deprecation warning is
fine for now.

Is this project open? If I can get the source I can dig into what the cause is.

**Comment by i4han** [comment]
Thanks!
Yes. It is open project.
https://github.com/i4han/insta

**Comment by i4han** [comment]
It deploys fine after removing coffeescript module.

**Comment by i4han** [comment]
One more problem was
I used "ꓸinit" as object key. "ꓸ" is not ascii dot (.) but unicode character http://j.mp/_dot_ 
            styl: o
                ꓸinit:  display:'none'
                ꓸtitle: display:'inline', fontWeight:'100'               
Modulus deploy is giving errors if "ꓸ" contains in the code.
It is legal to use as variables and keys in node.js and javascript. http://j.mp/javascript-identifiers
