### ISSUE TITLE
Windows version completely broken

### ISSUE THREAD

**Issue by Chos89** [onmodulus/demeteorizer#118]
Windows version completely broken -- nothing works with windows 0.3.0 version

**Comment by fiveisprime** [comment]
I can't say I'm super surprised by this since the version `0.3.0`
is being reused for Windows. :/

What is the output for `$ meteor --version` on Windows?

**Comment by Chos89** [comment]
WINDOWS-PREVIEW@0.3.0

Installing from npm install -g onmodulus/demeteorizer and now running demeteorizer gets me an error

Deleting node_modules folders.
fs.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy
^
Error: EPERM, operation not permitted 'C:\project\.demeteorized\programs\server\npm-shrinkwrap.json'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:887:18)

**Comment by Chos89** [comment]
BTW, not sure if meteor version 0.3.0 is being reused for windows, I think it just means that is what the windows version is at
windows-preview@0.3.0 /= meteor 0.3.0

But I could be wrong

**Comment by fiveisprime** [comment]
Looks like there's an issue resolving the path in Windows. The path
`C:\project.demeteorized\programs\server\npm-shrinkwrap.json` doesn't appear to
be valid.

What version of node are you using?

**Comment by Chos89** [comment]
v0.12.0

**Comment by Chos89** [comment]
Updated to v0.12.1 and getting a slightly different error now

Deleting node_modules folders.
fs.js:887
  return binding.unlink(pathModule._makeLong(path));
                 ^
Error: EPERM, operation not permitted 'C:\Users\ja-jo_000\RD\.demeteorized\programs\server\npm-shrinkwrap.json'

**Comment by Chos89** [comment]
is this related : 
http://stackoverflow.com/questions/24705002/strange-error-while-deleting-a-file-using-the-module-fs-in-node-js

**Comment by fiveisprime** [comment]
It's not exactly the same problem, the code is [here](https://github.com/onmodulus/demeteorizer/blob/master/lib/demeteorizer.js#L452) which is a proper
asynchronous loop.

I'm thinking the problem is that the pathing is relative to the current working
directory, which works on *nix systems (./folder/file.ext) but not on Windows
(folder/file.ext).

Is the path that is being returned even close to correct? Only missing the
path separator, right?

**Comment by Chos89** [comment]
Yes, the path is correct, I copyed my full path now, path separator is there, it just disapears when i copy it here and when i go to edit it appears, wierd

I discovered a big security bug and now I can't deploy the fix, before when i was running $ demeteorizer after 5,6 times it would work but now it just won't, like it knows it's important this time :)

**Comment by fiveisprime** [comment]
Try running from the new branch:
`$ npm install -g onmodulus/demeteorizer#windows-paths`

I changed the unlink code to completely resolve the path.

**Comment by Chos89** [comment]
Still getting the same error...

**Comment by fiveisprime** [comment]
Alright, let me see about spinning up a copy of Windows and
testing this.

Which version of Windows are you on?

**Comment by Chos89** [comment]
8.1

**Comment by Chos89** [comment]
Confirmed same issue with version 1.1-rc.1

**Comment by fiveisprime** [comment]
Install from the `#windows-path` branch again, delete the
`.demeteorized` directory, and rerun the script.

I'm still working on rerunning with the `.demeteorized` directory
there.

**Comment by Chos89** [comment]
Worked!!
Thanks man, you have a beer from me!

**Comment by fiveisprime** [comment]
Just pushed another change to the `windows-path` branch that should fix
removing the existing `.demeteorized` directory when rerunning
demeteorizer.

Try that out and let me know if you run into any other issues.

Thanks a lot for your patience with me while I work through this. :)

**Comment by Chos89** [comment]
That works too now :+1: 
No problem, I've also sent you an email but it seems it's faster to reach you here

**Comment by fiveisprime** [comment]
Haha yeah, I realized it was the same person and just took it all here. :+1:

**Comment by AndreasGalster** [comment]
I'm facing a few issues as well. Your update from the windows branch seems to have helped but there are still things that aren't working for me yet.

First of all, when I run demeteorizer anywhere except from my root I get this: 

PS C:\Users\Andreas Galster\Desktop\friendzone_app\www> demeteorizer
Input:  C:\Users\Andreas Galster\Desktop\friendzone_app\www
Output: C:\Users\Andreas Galster\Desktop\friendzone_app\www\.demeteorized
Determining Meteor version...
Meteor version: 0.1.7
Bundling Meteor App...
Demeteorization failed: Command failed: C:\Windows\system32\cmd.exe /s /c "cd C:\Users\Andreas\ Galster\Desktop\friendzo
ne_app\www && meteor bundle   --directory C:\Users\Andreas\ Galster\Desktop\friendzone_app\www\.demeteorized"
The system cannot find the path specified.




Another issue is being unable to do modulus deploy from the project root directory. I always need to go into .demeteorizer to do it. This fixed my deployment issues before today but now I'm getting a lot of log errors after deployment.

**Comment by fiveisprime** [comment]
@AndreasGalster what version of Windows are you on?

**Comment by AndreasGalster** [comment]
8.1

**Comment by fiveisprime** [comment]
@Chos89 Are you using cmd.exe or Powershell?

**Comment by fiveisprime** [comment]
@AndreasGalster is it possible for you to update to Meteor 0.3.0?

**Comment by AndreasGalster** [comment]
New message from my project root after updating. By the way, no .demeteorized folder created yet.

PS C:\Users\Andreas Galster\Desktop\friendzone_app\www> modulus deploy
Welcome to Modulus
You are logged in as AndreasGalster
[?] Are you sure you want to use project FriendzoneBeta? (yes) yes
Meteor project detected...
Input:  C:/Users/Andreas Galster/Desktop/friendzone_app/www
Output: C:\Users\Andreas Galster\Desktop\friendzone_app\www\.demeteorized
Determining Meteor version...
C:\Users\Andreas Galster\AppData\Roaming\npm\node_modules\modulus\node_modules\demeteorizer\lib\demeteorizer.js:122
    var version = versionText.split(' ')[1].trim();
                                           ^
TypeError: Cannot read property 'trim' of undefined
    at Demeteorizer.<anonymous> (C:\Users\Andreas Galster\AppData\Roaming\npm\node_modules\modulus\node_modules\demeteor
izer\lib\demeteorizer.js:122:44)
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
PS C:\Users\Andreas Galster\Desktop\friendzone_app\www>

**Comment by AndreasGalster** [comment]
Sorry, I should have added I did modulus deploy. I'll try demeteorizer now!

PS C:\Users\Andreas Galster\Desktop\friendzone_app\www> demeteorizer
Input:  C:\Users\Andreas Galster\Desktop\friendzone_app\www
Output: C:\Users\Andreas Galster\Desktop\friendzone_app\www\.demeteorized
Determining Meteor version...
Meteor version: 0.3.0
Bundling Meteor App...
Demeteorization failed: Command failed: C:\Windows\system32\cmd.exe /s /c "cd C:\Users\Andreas\ Galster\Desktop\friendzo
ne_app\www && meteor bundle   --directory C:\Users\Andreas\ Galster\Desktop\friendzone_app\www\.demeteorized"
The system cannot find the path specified.

PS C:\Users\Andreas Galster\Desktop\friendzone_app\www>

**Comment by fiveisprime** [comment]
Right right, I haven't published the Demeteorizer Windows updates
nor updated the Modulus CLI quite yet.

Once we get through all of the issues in demeteorizer, I'll publish it
and get the Modulus CLI updated. :+1:

**Comment by Chos89** [comment]
Yesterday there was a major update in meteor, all versions are now at 1.1, including windows.
And demeteorizer works for me on 1.1

**Comment by fiveisprime** [comment]
@Chos89 Thanks for the update! @AndreasGalster can you update
to the 1.1 version and try that?

**Comment by AndreasGalster** [comment]
Update what to 1.1? Which command do I need to run?

**Comment by Chos89** [comment]
Try meteor update and if that doesn't work you have now the official
installer for windows at meteor.com

2015-04-01 16:35 GMT+02:00, AndreasGalster <notifications@github.com>:

**Comment by fiveisprime** [comment]
Looks like you'll need to rerun the installer for Windows. Just tried
`$ meteor updated` on Windows@8.1 and it did nothing. Only the
installer got me to 1.1.

**Comment by fiveisprime** [comment]
I'm going to declare this "done" and ship a minor version with
Windows support unless either of you are still having issues.

**Comment by robertBrown** [comment]
Going to take it for a spin on windows 10

On Wednesday, April 1, 2015, Matt Hernandez <notifications@github.com>
wrote:

> I'm going to declare this "done" and ship a minor version with
> Windows support unless either of you are still having issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onmodulus/demeteorizer/issues/118#issuecomment-88589789>
> .
>


-- 


- Robert Brown

**Comment by fiveisprime** [comment]
Awesome, let me know what you find. I'd like to publish this today
(on April Fool's Day) :trollface:

**Comment by robertBrown** [comment]
Haha ok. I'll see what I can do

On Wednesday, April 1, 2015, Matt Hernandez <notifications@github.com>
wrote:

> Awesome, let me know what you find. I'd like to publish this today
> (on April Fool's Day) [image: :trollface:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onmodulus/demeteorizer/issues/118#issuecomment-88617449>
> .
>


-- 


- Robert Brown
