### ISSUE TITLE
demeteorizer cmd fails due to stderr maxBuffer exceeded...?

### ISSUE THREAD

**Issue by raghuugare** [onmodulus/demeteorizer#122]
Getting the following msg, as demeteorizer command fails on Amazon AWS EC2 instance running the following:

**OS:** RedHat Enterprise 7.x (x86_64)
**npm:** version 2.7.5
**Meteor:** version 1.1

The message I'm seeing is:

`Demeteorization failed: stderr maxBuffer exceeded.`

**Comment by sjmcdowall** [comment]
@fiveisprime -- I cloned and created a branch with a possible fix -- but when I tried to push the branch up I was denied.  I am probably just doing this all wrong. :)  How do I properly go about doing a pull request to put the changes in?

**Comment by fiveisprime** [comment]
Landed in demeteorizer@2.2.10
