### ISSUE TITLE
Possible to use multiple versions of same npm module?

### ISSUE THREAD

**Issue by hellogerard** [onmodulus/demeteorizer#125]
Let's say I have two Meteor packages. Both depend on the same npm module, but different versions. Currently, demeteorizer picks one over the other, I believe, and sticks in the top-level folder. `meteor build` keeps both versions. Is it possible for `demeteorizer` to do the same?

Original issue here: https://github.com/vsivsi/meteor-file-collection/issues/52

**Comment by robertBrown** [comment]
Gerard,

I'm pretty sure demeteorizer has been discontinued.  May want to talk to
Matt directly.





- Robert Brown

**Comment by hellogerard** [comment]
@fiveisprime @TheReddest Is this true? If so, what's the official stance of Modulus on Meteor?

**Comment by fiveisprime** [comment]
Not exactly.

We're working on making Meteor deployments easier and more seamless,
but Demeteorizer is not going away. We will continue to support and maintain
it. :)

As for the issue itself, we need a way for demeteorizer to check dependencies
of dependencies from package.js. We rely on package.json and npm to let the
child dependencies declare their dependencies, but that doesn't work for
package.js.

I'll see what I can come up with.

**Comment by calebl** [comment]
@fiveisprime any updates on this?

**Comment by robertBrown** [comment]
@fiveisprime <https://github.com/fiveisprime> what about $ demeteorizer
--checkdeps [package1.js, package2.js]

maybe the checkdeps script can parse packages, regex for Npm.depends({
packages }), export packages to demeteorized package.json before building
package.json?



- Robert Brown

**Comment by Jaetoh** [comment]
Hi there, any news about this issue ?

**Comment by fiveisprime** [comment]
@hellogerard This is potentially fixed in the beta version of demeteorizer.
Would you mind testing it out to see? Make sure you deploy using the `-m` flag
if you deploy to Modulus.

    $ npm install -g demeteorizer@next
    $ cd /path/to/project
    $ demeteorizer --architecture os.linux.x86_64
    $ modulus deploy .demeteorized/bundle -m

That should correctly handle dependencies as each package is built with its own
dependencies rather than forcing them into a package.json.

**Comment by hellogerard** [comment]
@fiveisprime This looks good!

Sorry for the delay. I couldn't find a good way to test this, and then I re-read my original issue linked above.  (We ended up working around this issue in the original project by taking a different route).

Over in the original issue I linked above, I had a simple reproduction that broke when deployed to Modulus. This reproduction is working now!

I didn't use the "manual" instructions you posted above. I simply ran `modulus deploy`. Hope that this still verifies. (I'm on modulus CLI 5.0.0).

**Comment by fiveisprime** [comment]
Awesome, that does indeed verify. :) Thanks :+1:

**Comment by robertBrown** [comment]
Thanks! Hey Gerard, what's up? Still @ differential?

On Tuesday, September 22, 2015, Matt Hernandez <notifications@github.com>
wrote:

> Closed #125 <https://github.com/onmodulus/demeteorizer/issues/125>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onmodulus/demeteorizer/issues/125#event-415990561>.
>


-- 


- Robert Brown
