### ISSUE TITLE
Failing to run when using the node-quickbooks package

### ISSUE THREAD

**Issue by andylash** [onmodulus/demeteorizer#127]
When I add the node-quickbooks npm package to my meteor app, demeteorizer appears to erroneously pick up the node-quickbooks-example-app as an npm module and add it as a dependency.  It shouldn't be as it's not listed as a dependency, it's just code that's sitting there and should be ignored.  

From what I can guess from the github issues, this has happened before and you're just making a static list of libraries to ignore?  https://github.com/onmodulus/demeteorizer/issues/126

**Comment by fiveisprime** [comment]
Landed in demeteorizer@2.2.4 which is available in modulus@3.10.3. This fix
ignores any/all packages with 'test', 'sample', or 'example' in the name.
