### ISSUE TITLE
Using ssl

### ISSUE THREAD

**Issue by okpatil4u** [onmodulus/demeteorizer#129]
Is it possible to use ssl for the connection with mongodb with demeteorizer ?

**Comment by fiveisprime** [comment]
I'm not sure I follow what you mean. Meteor makes the Mongo connection using the
connection string provided in the `MONGO_URL` or `METEOR_SETTINGS` environment
variables.

_How_ Meteor makes that connection (whether it provides `{ ssl: true }`) is up
to Meteor and it appears that there are no special cases for SSL like it does
for `auto_reconnect` - see [the driver connection source](https://github.com/meteor/meteor/blob/master/packages/mongo/mongo_driver.js#L127).

This isn't something that Demeteorizer can help with. :/
