### ISSUE TITLE
Quite often getting Segmentation Fault

### ISSUE THREAD

**Issue by rjakobsson** [onmodulus/demeteorizer#131]
We're quite often getting the following error, and failed builds when deploying to Modulus using demeteorizer: 

```
[Error] Error: Command failed: This command has been deprecated in favor of 'meteor build', which allows you
to build for multiple platforms and outputs a directory instead of a single
tarball. See 'meteor help build'for more information.


WARNING: The output directory is under your source tree.

Segmentation fault (core dumped)
```

**Comment by rjakobsson** [comment]
Any ideas as to why that is?

**Comment by fiveisprime** [comment]
What version of node are you on?

**Comment by rjakobsson** [comment]
I'm on 0.10.36.

**Comment by fiveisprime** [comment]
I haven't seen this error since back in the node@0.6 days. It will take some
time to track this one down and may very well have more to do with your
system/environment than demeteorizer.

**Comment by rjakobsson** [comment]
When I shrunk the size of my app under 10 MB, the issue has disappeared. Not sure if it's related, but I don't have this issue anymore.
