### ISSUE TITLE
bcrypt install failing on newer node versions

### ISSUE THREAD

**Issue by gferrin** [onmodulus/demeteorizer#132]
I demeteorized my app and when I ran `npm install` I got this error:
```
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sites/meteor-app/.demeteorized/npm-debug.log
```

upon further inspection is seems that certain versions of node are only compatible with [certain bcrypt versions](https://github.com/ncb000gt/node.bcrypt.js/blob/master/README.md#version-compatibility)

## Version Compatibility

| Node Version | Bcrypt Version |
| ---- | ---- |
| 0.4.x | <= 0.4.x |
| 0.6.x | >= 0.5.x |
| 0.8.x | >= 0.5.x |
| 0.10.x | >= 0.5.x |
| 0.11.x | >= 0.8.x |

and when I checked `package.json` it seems that demeteorizer was hard linking to:
https://registry.npmjs.org/bcrypt/-/bcrypt-0.7.8.tgz

changing my package to 
`"bcrypt": "*",`

seemed to fix the problem though `*` is probably not the correct solution either.

**Comment by fiveisprime** [comment]
Meteor is currently only compatible with node@0.10.33, which is why it's using
an older version of bcrypt. You'll have to run the demeteorized application
under node@0.10.33.

See #128 for more on this.

**Comment by gferrin** [comment]
Okay thanks. Is that just for the compilation step or does my server also need to be running node@0.10.33?

**Comment by fiveisprime** [comment]
The server needs to be on node@0.10.33 as well. The generated package.json from
the demeteorize step does correctly specify the node version if that helps with
your deployment. :)
