### ISSUE TITLE
Run `npm install` by default

### ISSUE THREAD

**Issue by taromero** [onmodulus/demeteorizer#133]
I think it would be useful if `demeteorizer` could run `npm install` automatically, either by default or by supplying some argument.

Currently, after running demeteorizer, I have to run:

- `cd demeteorizer/programs/server`
- `npm install`
- `cd ../..`

This is easily achievable by wrapping `demeteorizer` on a bash script, but it might be useful to have it built in.

**Comment by fiveisprime** [comment]
This is outside of the scope of demeteorizer.
