### ISSUE TITLE
Failing on Windows 7 with Meteor 1.1.0.3 -- Command failed: The system cannot find the path specified

### ISSUE THREAD

**Issue by sjmcdowall** [onmodulus/demeteorizer#134]
demeteorizer version : 2.2.7

I just updated my meteor app to 1.1.0.3 on windows and am trying to demeteorizer it -- now I get the following error: 

C:\Users\Steven McDowall\work\galaxy\rts\sources\RTViewer>demeteorizer -o c:\dep
loy\Galaxy\RTViewer
Input:  C:\Users\Steven McDowall\work\galaxy\rts\sources\RTViewer
Output: c:\deploy\Galaxy\RTViewer
Determining Meteor version...
Meteor version: 1.1.0.3
Output folder exists, deleting...
Bundling Meteor App...
Demeteorization failed: Command failed: The system cannot find the path specifie
d.

Any ideas? Would be nice if it would print out the "path" it can't find... 

Thanks!

P.S. The same app can be demeteorized just fine on my Mac with the same 2.2.7 version, so this looks like a Windows specific issue... ?? 

P.S.S.  It appears it's because I have a space in the Input name (output may do the same) -- looks like demeteorizer will "escape" the space even in Windows with a "\ " .. but Windows of course uses \ as a path delimiter .. hence it can't find the input directory (even though it's already in there) .. 

Not sure of the best way to fix the bug though .. I implemented what maybe a hack with this code -- but it seems to work .. by simply not doing any escaping on Windows.. but I'm no windows expert so not sure the ramifications .. 

var os           = require('os') ;

const modulesNotInRegistry = [
  'aws-sdk-browser-builder',
  'nw-pre-gyp-module-test',
  'forge-nodejs-example'
];

/**
 * Escapes special characters out of the specified path.
 * @param {String} filePath The path to escape.
 */
var escapePath = function (filePath) {
  if (!filePath || filePath.length === 0) return filePath;

  // SJM - It doesn't look like we should do any escaping of the filepath if we are in Windows..
  if ( os.platform().substring(0,3) !== 'win' ) {
    filePath = filePath.replace(/ /g, '\\ ');
    filePath = filePath.replace(/\&/g, '\\&');
    filePath = filePath.replace(/\(/g, '\\(');
    filePath = filePath.replace(/\)/g, '\\)');
  }
  return filePath;
};

**Comment by fiveisprime** [comment]
Looks like there are still some compatibility issues with Windows.

Thanks for the detailed report. :)

**Comment by fiveisprime** [comment]
Try using the branch `#path-escaping` and see if that corrects the issue.

**Comment by sjmcdowall** [comment]
I'll give it shot tomorrow when I'm back at my "normal" Windows workstation ...

**Comment by sjmcdowall** [comment]
OK -- this is a bit embarrassing -- but how do I try out that branch?  Some npm install option or ?? 

Thanks

**Comment by fiveisprime** [comment]
Install the module from this repo/branch:

`$ npm install -g onmodulus/demeteorizer#path-escaping`

:+1:

**Comment by sjmcdowall** [comment]
Ok!

Tried it on both Windows and Mac OSX and it appears to be working much better!

**Comment by fiveisprime** [comment]
The fix is live in demeteorizer@2.2.9

Thanks for reporting this!
