### ISSUE TITLE
Windows 7 leaderboard npm install Fail

### ISSUE THREAD

**Issue by skyrack2** [onmodulus/demeteorizer#138]
On Windows 7, I am getting console errors:

gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\nod
les\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd c:\wamp\www\meteor\leaderboard\.demeteorized\node_modules\fib
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
Build failed
npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.

and in the debug.log:

2343 error fibers@1.0.5 install: `node ./build.js`
2343 error Exit status 6
2344 error Failed at the fibers@1.0.5 install script.
2344 error This is most likely a problem with the fibers package,
2344 error not with npm itself.
2344 error Tell the author that this fails on your system:
2344 error     node ./build.js
2344 error You can get their info via:
2344 error     npm owner ls fibers
2344 error There is likely additional logging output above.
2345 error System Windows_NT 6.1.7601
2346 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2347 error cwd c:\wamp\www\meteor\leaderboard\.demeteorized
2348 error node -v v0.10.22
2349 error npm -v 1.3.14
2350 error code ELIFECYCLE

Any help on this is greatly appreciated.

**Comment by sjmcdowall** [comment]
Not a perfect so,union but for now

1- update to node 0.10.36

2 - hand modify the package.json file and replace the fibers entry from the long URL to simply "1.0.5"

Btw - not a demeteorizer issue but Meteor with bug file but no movement

**Comment by sjmcdowall** [comment]
Oh and do a 

npm cache clear

Before next npm install

**Comment by skyrack2** [comment]
Thanks,

1- update to node 0.10.36 has me beaten for now?

I have npm but not sure what the CLI command is for this, nor how to
upgrade any other global installs I have.

Any pointers for this?

And when that done and the other points you mentioned, should I start
again with a new leaderboard project, or can I pick up at the install
command?

Thanks for your help,

**Comment by sjmcdowall** [comment]
Look for something called nvm - Google it - it's a node version manager 

Should be able to get you up to the right node 

Should be no reason to have to start fresh - just continue

**Comment by skyrack2** [comment]
Many Thanks for your kind help

**Comment by skyrack2** [comment]
After a lot of kerfuffle I got nvm installed and node is now running 0.10.36.
Followed your instructions.

And got message to re-install fibers which I did.

And MAGIC it works!

Your help is much appreciated.

Now I will try and deploy this remotely....

**Comment by fiveisprime** [comment]
🎉

Let us know if you run into any more issues.

Thanks a lot for helping out @sjmcdowall :+1:

**Comment by sjmcdowall** [comment]
@skyrack2 -- remember if you deploy remotely -- that remote setup must be identical to the one you demeteorized under.  Same node version , same basic architecture (Windows), etc. Have fun!

@fiveisprime -- no worries.  Love this project.  Plan to do more PRs when I get a moments breath . )
