### ISSUE TITLE
Error: Cannot find module 'fibers'

### ISSUE THREAD

**Issue by navinpai** [onmodulus/demeteorizer#14]
The Demeteorized app does not run and gives a cannot find module 'fibers' error.
Steps to reproduce:
1) meteor create --example leaderboard
2) npm install -g demeteorizer
3) cd leaderboard
4) demeteorizer

``` bash
Input: /myfolder/leaderboard
Output: /myfolder/leaderboard/.demeteorized
Creating output folder.
Bundling Meteor App...
meteor bundle generation complete.
Extracting bundle.
Extraction complete.
Finding dependencies...
21 dependencies found.
Creating package.json file.
package.json file generation complete.
Setting minimum node version to v0.8.18
Deleting node_modules folders.
Deleting bundle tar.gz file.
Demeteorization complete.
```

5) cd .demeteorized
6) node main.js

``` javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/myfolder/leaderboard/.demeteorized/server/server.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I am unsure why this is happening though....

**Comment by kingluddite** [comment]
Every now and then I get this fibers error and it tends to happen when I git pull my meteor project on a different computer.

The fastest way I find to get back to coding is just curling meteor again.

curl https://install.meteor.com | /bin/sh

Works every time.

**Comment by wastedige** [comment]
Thanks kingluddite! I work on the same code using a Mac at work and a PC at home, and this problem occurs every few days.

**Comment by caltrain** [comment]
Thanks @kingluddite, it works!
