### ISSUE TITLE
Use build rather than bundle

### ISSUE THREAD

**Issue by fiveisprime** [onmodulus/demeteorizer#140]
The bundle command has been deprecated for a while and problems are starting to
pop up with the structure that `bundle` creates over `build`. It's time to fix
this.

Demeteorizer will need to be rewritten to support build. This will all happen on
a new branch that will be published as demeteorizer@next, which will be
published as it's completed.

I'll keep this issue updated with progress.

**Comment by sjmcdowall** [comment]
+1 -- fairly big job, but much needed.. especially as Meteor continues to evolve .. not even sure when 1.2 comes out how well the old bundle command will work for complex apps.

**Comment by fiveisprime** [comment]
Started on this in the [next](https://github.com/onmodulus/demeteorizer/tree/next) branch. You are welcome to start testing it out, but
I haven't documented a lot of how to use it (it's slightly different).

Running `$ demeteorizer` will generate the same `.demeteorized` directory, but
if you want to deploy that to Modulus, you'll have to run `modulus deploy .demeteorized/bundle`

**Comment by fiveisprime** [comment]
Just published the first demeteorizer alpha (v3.0.0-alpha.1), feel free to test it
out: `$ npm install -g demeteorizer@next`

I'll keep the `next` tag updated as I push alphas.
