### ISSUE TITLE
Project local 'package.json' leads to npm install error

### ISSUE THREAD

**Issue by Soulou** [onmodulus/demeteorizer#145]
In the case of the package https://github.com/nodejs/nan, the repository contains a directory named 'tools'.

In it, a package.json with an example of use of the package https://github.com/nodejs/nan/blob/master/tools/package.json

Problem is that after demeteorizing the application, there is a dependency '1to2' in the final package.json. However this package does not exist and `npm install` fails with a 404, what's the good way to do?

Regards,

-- Léo

**Comment by fiveisprime** [comment]
Is this on latest or next?

If on latest, try running from the next tag. :)

**Comment by remcoder** [comment]
I had the exact same issue. Using the next tag there is no error about missing dependencies. But how can this version be used with modulus-cli?

**Comment by sjmcdowall** [comment]
And -- if running on Windows, may want until my PR #144 is merged into master / next.

**Comment by Soulou** [comment]
It's on latest, will try again on next, thanks

**Comment by fiveisprime** [comment]
Once this is out of beta, I'll get it added to the Modulus CLI, until then,
you'll have to deploy the generated bundle.

*Make sure you include the `-m` flag.*

    $ npm i demeteorizer@next
    $ cd /path/to/project
    $ demeteorizer
    $ modulus deploy .demeteorizer/bundle -m

**Comment by remcoder** [comment]
thx! I got it working now :+1:

**Comment by remcoder** [comment]
btw, for future reference, `-g` was missing and the generated dir is `.demeteorized`

    $ npm i -g demeteorizer@next
    $ cd /path/to/project
    $ demeteorizer
    $ modulus deploy .demeteorized/bundle -m

**Comment by fiveisprime** [comment]
Updated, I've typed "demeteorizer" enough in the last week that it's automatic..

**Comment by ecwyne** [comment]
@fiveisprime is this still the best way to deploy to modulus? (including the `-m` flag)

What is the best way to deploy to modulus?

**Comment by fiveisprime** [comment]
@ecwyne the Modulus CLI tool has been updated to use the latest version of demeteorizer. There's no need to follow those steps anymore. :)

**Comment by ecwyne** [comment]
@fiveisprime which of the following would you suggest 

```sh
cd path/to/project/root
demeteorizer
cd .demeteorized
modulus deploy -p project-name
```

or

```sh
cd path/to/project/root
modulus deploy -p project-name
```

**Comment by fiveisprime** [comment]
Option 2, just deploy. :)

Option 1 still requires `-m`
