### ISSUE TITLE
--architecture flag is ignored in beta.2

### ISSUE THREAD

**Issue by remcoder** [onmodulus/demeteorizer#146]
I work on OS X and I was unable to cross-compile my application which has a dependency on xml2json which builds a binary. This is the command I used: `demeteorizer --architecture os.linux.x86_64`. I also used the `-m` option to deploy to modulus. 

Using `meteor build --architecture os.linux.x86_64` I was able to create a runnable application though.

**Comment by fiveisprime** [comment]
Published in demeteorizer@3.0.0-beta.3 and updated the `next` tag.

Thanks for the report! :+1:

**Comment by remcoder** [comment]
Nice. Thx for the timely fix! :D
