### ISSUE TITLE
Demeteorized app - error on "npm install"

### ISSUE THREAD

**Issue by trevordowdle** [onmodulus/demeteorizer#147]
I am on Mac OSX Yosemite, node V 4.0.0

The project has a dependency on fibers 1.0.5 and errors out during installation.

Any help or insight would be greatly appreciated.

node) child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:132:44: error: too many arguments to function call, expected at
      most 2, have 4
                return Signature::New(isolate, receiver, argc, argv);
                       ~~~~~~~~~~~~~~                    ^~~~~~~~~~
/Users/.../.node-gyp/4.0.0/include/node/v8.h:4675:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
../src/fibers.cc:140:3: error: no member named 'SetResourceConstraints' in
      namespace 'v8'; did you mean simply 'SetResourceConstraints'?
                v8::SetResourceConstraints(isolate, constraints);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                SetResourceConstraints
../src/fibers.cc:139:7: note: 'SetResourceConstraints' declared here
        void SetResourceConstraints(Isolate* isolate, ResourceConstraint...
             ^
2 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/.../Meteor/boldvueDeploy/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1

**Comment by sjmcdowall** [comment]
Meteor is supported only on Node 0.10.36 (regardless of the old README). Make sure to use that version.  There should be a compiled Fibers binary for Mac OS X 0.10.36 (I use it all the time).  Remember also that you must "npm install" ON the architecture you want to run on.  Doing an NPM INSTALL on Mac OS X and shipping everything to a Linux machine (or Windows) to run will NOT work.

**Comment by trevordowdle** [comment]
Ahh thanks for the info, I appreciate it.  As far the architecture I want to run on, I am attempting to run it using "Azure Web App service" do you by chance know what architecture would apply in this situation?

**Comment by sjmcdowall** [comment]
No -- never used Azure (anything).  However, I would be hard pressed to guess that it is not running under a Windows scheme. :) .  This is a pretty difficult combination to choose -- development on Mac OS X and deployment on a Windows PaaS.  Unless you can run an "npm install" on the remove PaaS before launching -- you will (I think) need to configure a Windows machine (including VS Express 2012) to demeteorize / npm install.  Once that works (and it may take a few times to get everything right) , you can bundle the whole thing up with however you do that to Azure and it "should" run.  That's my best guess.  Make sure you can control the node version on Azure to 0.10.36 too, or can you bundle node with the package (?).  Again, not sure about Azure Web App at all . 

Good look!

**Comment by trevordowdle** [comment]
Oh okay, i'll work on setting up a vm where I can go through the demeteorize process and git it a go.  Thank you for your advice and insight.  It is greatly appreciated :)
