### ISSUE TITLE
Issue with demeteorizer building iOS and Android folders as well as the bundle folder 

### ISSUE THREAD

**Issue by rjakobsson** [onmodulus/demeteorizer#148]
I believe that our build process is breaking on linux as the meteor build tool generates iOS and Android folders, but the build process can't access iOS or Android build tools as those tools are not available on the temporary build machine. This started happening after 3.0. Does this sound reasonable?

**Comment by sjmcdowall** [comment]
How exactly are you launching demeteorizer?  With what options?  I use it (3.0) just fine on Windows 7 which also does not have any tools for building iOS or Android with any issue.  Of course my application doesn't have those architectures listed as being valid either because it doesn't run on them.  :)

**Comment by rjakobsson** [comment]
If your project have added both the android and the iOS platform packages, then Meteor will always try and build those artifacts as well, which is an issue while deploying from a temporary linux machine (CI).

**Comment by sjmcdowall** [comment]
Ah -- so for "production" you will need to build all the platforms, but not for CI. Alas, I'm not an ISOBuild (the build part) .. I am pretty sure demeteorizer will take any additional parameters passed to it, and pass it to "build" .. but I don't know if there is a way to turn off platforms on the build.. ??

**Comment by rjakobsson** [comment]
That's the issue I think, there is currently no way to pick platforms via `meteor build`. I'm filing a feature request in the meteor repo. Until then, I think that this should be solvable by just deploying the stuff in the `bundle` directory (which maybe is more of a modulus cli issue than a demeteorized issue).

**Comment by fiveisprime** [comment]
I just ran into this after updating to 1.2.0.1. :(

I had to run `$ meteor remove-platform android` before converting since I don't
have the ADK installed.

**Comment by rjakobsson** [comment]
It worked for me after reverting to modulus@4.0.2, which doesn’t use demeteorizer 3.0.

**Comment by mariobriggs** [comment]
when using demeteorizer 3.0.with my app, it fails both on Mac OSX and linux. On both platforms only the 'bundle' folder is created under output folder. On Mac, i get this error message
 ``` 
Errors prevented bundling:                    
While processing files with templating (for target web.browser):
output/bundle/programs/web.browser/head.html:1: Expected one of: <body>, <head>, <template>

Conversion failed.  
```

it works if i rollback to meteor 2.31.

my app is [here](https://github.com/mariobriggs/meteor-accounts-couchdb/tree/master/app) if it helps

**Comment by sjmcdowall** [comment]
Is this Meteor 1.2 or 1.1?  Also, what node version would you be running "natively"?  I.e.  "node --version" from the command line gives?  

Not sure any of the above will help -- but it is of interest.  Any special packages, etc. in the project?  Perhaps a "meteor list" would indicate something of interest as well.

**Comment by mariobriggs** [comment]
the .meteor/ folder is in the git, so take a look at the release and versions file. node version locally is v0.12.4

**Comment by fiveisprime** [comment]
This is resolved with the `--server-only` or `-w` option.
