### ISSUE TITLE
New updates does not seems to run 

### ISSUE THREAD

**Issue by hdudeja** [onmodulus/demeteorizer#149]
0 info it worked if it ends with ok
1 verbose cli [ '/opt/mount1/node-v0.12.7-linux-x64/bin/node',
1 verbose cli   '/opt/mount1/node-v0.12.7-linux-x64/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart meteor-dev-bundle@0.0.0
6 info start meteor-dev-bundle@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info meteor-dev-bundle@0.0.0 Failed to exec start script
9 verbose stack Error: meteor-dev-bundle@0.0.0 start: `node ../../main`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/mount1/node-v0.12.7-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/opt/mount1/node-v0.12.7-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid meteor-dev-bundle@0.0.0
11 verbose cwd /opt/mount1/projects/b2bMarketplace/B2B_Marketplace/demeteorize/bundle/programs/server
12 error Linux 2.6.32-504.12.2.el6.x86_64
13 error argv "/opt/mount1/node-v0.12.7-linux-x64/bin/node" "/opt/mount1/node-v0.12.7-linux-x64/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error meteor-dev-bundle@0.0.0 start: `node ../../main`
17 error Exit status 1
18 error Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
18 error This is most likely a problem with the meteor-dev-bundle package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ../../main
18 error You can get their info via:
18 error     npm owner ls meteor-dev-bundle
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by sjmcdowall** [comment]
Can you give a bit of background on what exact command you entered / did to see the above? 

You do know that Meteor only supports node 0.10.36, not anything in the 0.12 or 4.x line, right?

**Comment by harlanj** [comment]
@hdudeja If this is still an issue please let us know. Closing the issue for now though.
