### ISSUE TITLE
Unable to deploy on windows (npm start error)

### ISSUE THREAD

**Issue by prasadnpawar** [onmodulus/demeteorizer#150]
Here is the error
C:\myMeteorApp\converted\bundle\programs\server>npm start

> meteor-dev-bundle@0.0.0 start C:\myMeteorApp\converted\bundle\programs\server
> node ../../main

C:\myMeteorApp\converted\bundle\programs\server\node_modules\fibers\future.js:24
5
                                                throw(ex);
                                                      ^
Error: The specified procedure could not be found.
C:\myMeteorApp\converted\bundle\programs\server\npm\npm-bcrypt\node_modules\bcry
pt\build\Release\bcrypt_lib.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (C:\myMeteorApp\converted\bundle\programs\server\npm\npm-bcrypt\
node_modules\bcrypt\node_modules\bindings\bindings.js:74:15)
    at Object.<anonymous> (C:\myMeteorApp\converted\bundle\programs\server\npm\n
pm-bcrypt\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\myMeteorApp\converted\bundle\programs\server\npm-debug.log

C:\myMeteorApp\converted\bundle\programs\server>

Please let me know the problem if anybody knows it.
Thanks,

**Comment by fiveisprime** [comment]
This is an issue with bcrypt running on Windows for the wrong target. That error
is from Windows rather than Node/bcrypt and has to do with how bcrypt is
compiled (Windows is unable to load the DLL).

First, try running the application under node@0.10.36 as Meteor applications
won't run under 0.12.x and your bcrypt module is compiled to 0.10.x. If that
doesn't solve the issue, you may need to recompile bcrypt to work on your
system.

**Comment by prasadnpawar** [comment]
I tried node js version 0.10.36 on my other windows 7 machine where I have build tools of VS2010 and I got error while running npm install

C:\myMeteorApp\converted\bundle\programs\server>npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
\


> fibers@1.0.5 install C:\myMeteorApp\converted\bundle\programs\server\node_modu
les\fibers
> node ./build.js

-
C:\myMeteorApp\converted\bundle\programs\server\node_modules\fibers>node "C:\Pro
gram Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\no
de-gyp\bin\node-gyp.js" rebuild --release
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(362,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\myMeteorApp\converted\bundle\programs\server\node_modules\fibers
\build\fibers.vcxproj]
  fibers.cc
  coroutine.cc
c:\users\sinppw\.node-gyp\0.10.36\deps\uv\include\uv-private/uv-win.h(32): fata
l error C1083: Cannot open include file: 'winsock2.h': No such file or director
y (..\src\coroutine.cc) [C:\myMeteorApp\converted\bundle\programs\server\node_m
odules\fibers\build\fibers.vcxproj]
c:\users\sinppw\.node-gyp\0.10.36\deps\uv\include\uv-private/uv-win.h(32): fata
l error C1083: Cannot open include file: 'winsock2.h': No such file or director
y (..\src\fibers.cc) [C:\myMeteorApp\converted\bundle\programs\server\node_modu
les\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\myMeteorApp\converted\bundle\programs\server\node_modules\fibers

gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
Build failed

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\myMeteorApp\converted\bundle\programs\server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\myMeteorApp\converted\bundle\programs\server>npm start

> meteor-dev-bundle@0.0.0 start C:\myMeteorApp\converted\bundle\programs\server
> node ../../main


module.js:340
    throw err;
          ^
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\myMeteorApp\converted\bundle\programs\server\boot.
js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\myMeteorApp\converted\bundle\programs\server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\myMeteorApp\converted\bundle\programs\server\npm-debug.log
npm ERR! not ok code 0

**Comment by sjmcdowall** [comment]
Unfortunately you need to install a MS VStudio including setting it up for command line building - VS2015 Express is ok but beware the C++ stuff is not optional so choose Custom install

**Comment by dotnetwise** [comment]
Perhaps depending on your installed VS I have managed to install `node-gyp` by setting `msvs_version` to target VS2013 although I have both vs2013 and vs2015 installed
```js
npm config set msvs_version 2013
```
