### ISSUE TITLE
regression: when running demeteorizer, the platform used is darwin

### ISSUE THREAD

**Issue by Soulou** [onmodulus/demeteorizer#152]
I'm running on a Linux 64bits machine:

``` bash
# dfischer:phantomjs installs the npm module phantomjs-sun
# which reads the 'process.platform' variable (https://github.com/gadicc/phantomjs/blob/master/install.js)

$ meteor add dfischer:phantomjs
$ demeteorizer -a os.linux.x86_64
$ file .demeteorized/bundle/.../phantom/bin/phantomjs
.demeteorized/bundle/.../phantom/bin/phantomjs: Mach-O i386 executable
```

It is as if the platform was not used at all in the installation of the npm package. Any hint about that?

I'm saying it's a regression because with pre-v3.x versions, the package was added to the `package.json`, and during the `npm install` the correct platform was used by npm and I got the linux version of `phantomjs`

**Comment by fiveisprime** [comment]
So, the `architecture` option is kind of weird... It's passed down to build, but
packages don't necessarily _have_ to honor it. This is the case here. If the
module isn't compiled for the target arch and doesn't have a step for
recompiling on build, you get this. :(

**Comment by fiveisprime** [comment]
Is this still an issue? It seems impossible for Meteor to compile for a target other than the current platform - so even specifying `--architecture` may nor work correctly. :(

It looks like you've come up with some workarounds for this anyway, correct?
