### ISSUE TITLE
App is buggy with upgrade to Meteor v1.2.0.2?

### ISSUE THREAD

**Issue by fvpDev** [onmodulus/demeteorizer#153]
I've done many upgrades of meteor + packages since my last deployment into production modulus environment, so I am not sure, but it seems that since the Meteor v1.2.0.2 upgrade my app is failing.
See console log: http://joes-ny-pizzeriawebsite-53475.onmodulus.net/

It's working flawlessly in local environment; so I have no idea...

**Comment by fvpDev** [comment]
Update #1:

Trying to re-create the problem; seems a lot of people are running into this issue.
Getting this during deployment process:
```
make: Entering directory `/mnt/input/K/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_forJNYP2/.demeteorized/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
../src/coroutine.cc:64:53: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
  for (pthread_key_t ii = coro_thread_key - 1; ii >= 0; --ii) {
                                                     ^
../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tls == thread_id) {
   ^
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/mnt/input/K/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_forJNYP2/.demeteorized/bundle/programs/server/node_modules/fibers/build'
Installed in `/mnt/input/K/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_forJNYP2/.demeteorized/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
meteor-dev-bundle@0.0.0 /mnt/input/K/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_forJNYP2/.demeteorized/bundle/programs/server
├── ansi-regex@0.2.1
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── fibers@1.0.5
├── has-ansi@0.1.0
├─┬ meteor-promise@0.5.0
│ └─┬ promise@7.0.4
│   └── asap@2.0.3
├── semver@4.1.0
├─┬ source-map-support@0.3.2
│ └─┬ source-map@0.1.32
│   └── amdefine@1.0.0
├── strip-ansi@0.3.0
├── supports-color@0.2.0
├── type-of@2.0.1
└── underscore@1.5.2

npm WARN EPACKAGEJSON meteor-dev-bundle@0.0.0 No description
npm WARN EPACKAGEJSON meteor-dev-bundle@0.0.0 No repository field.
npm WARN EPACKAGEJSON meteor-dev-bundle@0.0.0 No license field.
v0.10.40
deploy -> v0.10.40
Uploading completed build.
Provisioning and deploying bundle to servos...
```
Once deployed client console log gives warning(s):
```
pathFor couldn't find a route named "home"
Exception from Tracker recompute function:
TypeError: Cannot read property 'getName' of undefined
    at l (15b5f9fcda3d74e5a677941a4c2cd5187e087a6a.js:154)
    at 15b5f9fcda3d74e5a677941a4c2cd5187e087a6a.js:154
    at t.Computation._compute (15b5f9fcda3d74e5a677941a4c2cd5187e087a6a.js:40)
    at t.Computation._recompute (15b5f9fcda3d74e5a677941a4c2cd5187e087a6a.js:40)
    at Object.t._runFlush (15b5f9fcda3d74e5a677941a4c2cd5187e087a6a.js:40)
    at e (15b5f9fcda3d74e5a677941a4c2cd5187e087a6a.js:5)
```

Update: while recreating with new meteor project (via `meteor create`), in order to fix Tracker error^ I have included iron:router@1.0.12:
```
Router.route("/(.*)", {
	name: "notfound"
});
```
Then added that back to full app and redeployed only to get same error...
Seems to be in relation to meteor `ejson` package based on console log.

More updates coming during problem recreation process (via adding code little by little and extensive re-deployments and testing)

**Comment by dagatsoin** [comment]
I have a similar issue when I use a recent version of Node.js

Try to use node 0.10.40, it works for me.

**Comment by sjmcdowall** [comment]
Meteor 1.2.X only supports Node 0.10.40 - period.  I think the issue is that in Meteor 1.2 the package system is a bit more stringent in that packages need to properly have the right manifests for dependencies, etc. and some of them haven't been fixed.  That could be the problem with the ejson package?   

What happens if you demeteorize the package to somewhere local and then try to actually run it ?? (following the README to set it up?)

**Comment by fvpDev** [comment]
Node version is 0.10.40 (see original log above).

Ok...so the problem was that I had a pdf file that I was going to use as a "printable version" of the restaurant menu located in /public/menu and I was simply trying to have it open with an href. I removed the pdf file from the structure and everything worked smoothly. Plan is to move on just using a media query for print the info, but I'd rather have it as a pdf file of course, for downloading purposes (I have not looked into how to include a pdf in a meteor app, however the file was ~40mb, so I'm not quite sure what exactly the problem was).

Btw, semi-newbie here.

**Comment by fvpDev** [comment]
Since we're talking about node versions now...
#154
