### ISSUE TITLE
package.js - Unable to determine Node version.

### ISSUE THREAD

**Issue by fvpDev** [onmodulus/demeteorizer#154]
Newbie confused:

Ok, so I am deploying the same application to modulus I just deployed a few days ago (haven't updated anything at all) and now I'm getting this:
```
Compressing project...
21.9 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Node.js runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /K/OneDrive/_fvpDev/SRS/Google Drive/Clients/Joe's New York Pizzeria/website/_webRoot/.demeteorized/bundle/programs/server/package.json
Unable to determine Node version. Verify package.json has no errors.
Build attempt failed, attempting again.
```

The local package.js under /.demeteorized:
```
{
  "name": "meteor-dev-bundle",
  "version": "0.0.0",
  "dependencies": {
    "fibers": "https://github.com/meteor/node-fibers/tarball/d519f0c5971c33d99c902dad346b817e84bab001",
    "meteor-promise": "0.5.0",
    "underscore": "1.5.2",
    "source-map-support": "https://github.com/meteor/node-source-map-support/tarball/1912478769d76e5df4c365e147f25896aee6375e",
    "semver": "4.1.0"
  },
  "devDependencies": {
    "eachline": "https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da",
    "chalk": "0.5.1"
  },
  "engines": {
    "node": "0.10.40"
  },
  "main": "../../main.js",
  "scripts": {
    "start": "node ../../main"
  }
}
```

Still using Meteor v1.2.0.2 not v1.2.1

Same result after updating to 1.2.1.

Same result after upgrading node to 5.x

**Comment by sonicviz** [comment]
Getting same error trying to deploy. Not impressed so far with the "ease of use".
MUP on AWS works just fine.

**Comment by sjmcdowall** [comment]
Perhaps writing the to Modulus group / support?  This is for basically only the demeteorizer tool, one step in the process and I use it almost daily without issue (but I do not deploy to Modulus) .  It doesn't seem like there is an issue with demeteorizer (or it's very buried)

**Comment by sonicviz** [comment]
You're right. I moved onto scalingo.com and their demetorizer deployment worked just fine. Must be a modulus issue but It's up to them to figure it out. Sorry to bother you!

**Comment by fiveisprime** [comment]
This tends to happen when deploying from a directory that doesn't have a pakcage.json or, it seems, deploying from Windows.

See https://github.com/onmodulus/modulus-cli/issues/61
