### ISSUE TITLE
Windows server question

### ISSUE THREAD

**Issue by cope** [onmodulus/demeteorizer#156]
From the [Examples](https://github.com/onmodulus/demeteorizer#examples) section I understand that there are some environment variables that need to be set in order to run the demeteorized nodejs application.

1. How would these variables be defined on a Windows server?

2. Is it possible to have these in a configuration file as part of the nodejs app itself, so that more than one meteor nodejs app can be deployed on the same server (*using different mongo dbs and ports*)?

3. The middle `step npm` install` here:
```
$ cd /your/output/directory/bundle/programs/server
$ npm install
$ MONGO_URL=mongodb://localhost:27017/test PORT=8080 ROOT_URL=http://localhost:8080 npm start
```
...does that install the demeteorized nodejs application, like any other nodejs app?

--------
**And, most importantly:**
4. Do you know how to answer (*and get the bounty for*) this question in detail, with using demeteorizer: http://stackoverflow.com/q/33829284/271873

**Comment by fiveisprime** [comment]
1. Try `$ set MONGO_URL=mongodb://localhost:27017/test && set PORT=8080 && set ROOT_URL=http://localhost:8080 $$ npm start`

2. This is outside of the scope of Demeteorizer

3. The `npm install` will install the dependencies required by the generated
   application. Also, be sure that you are using the correct version of node
   when running this part - the correct version is in the generated package.json

4. Looks like that is already answered :)

Sorry it took so long to get to this!
