### ISSUE TITLE
Meteor not in Path

### ISSUE THREAD

**Issue by louis49** [onmodulus/demeteorizer#157]
When meteor is not in the path, the error message displayed is not clear : 

Error: spawn ENOENT

**Comment by harlanj** [comment]
@louis49 `demeteorizer` utilizes the `meteor` command. If it's not in your `PATH` correctly, then you would be experiencing this error. Can you confirm that `meteor` is correctly set in your path? And if this is no longer an issue let us know so we can close this.

**Comment by sjmcdowall** [comment]
@harlanj -- I think you missed the point of the issue.  It's not that meteor isn't there (it isn't) -- but rather that the ERROR MESSAGE for this condition is less than helpful.  An ENOENT error is vague and not helpful.  The idea here is to change the error message to something helpful like "meteor command not found : please make sure meteor is in your PATH".  

:)

**Comment by louis49** [comment]
@sjmcdowall 👍

**Comment by harlanj** [comment]
@louis49 @sjmcdowall ah I see. My bad on that. I'm not sure if that message can ONLY mean that Meteor isn't in the path. Using the latest version of `demeteorizer`, the output looks like the following:

```
$ demeteorizer
Demeteorizing application...
spawn meteor ENOENT
```

If this can ONLY mean that meteor isn't in the path/installed, then I can have a PR ready.

**Comment by jackboberg** [comment]
I think if we look for the error [here](https://github.com/onmodulus/demeteorizer/blob/master/lib/build.js#L38-L40) it can only be referencing `meteor`.

**Comment by harlanj** [comment]
@louis49 @sjmcdowall I opened a PR addressing this. #210
