### ISSUE TITLE
Error at npm install mac os x

### ISSUE THREAD

**Issue by Cu4rach4** [onmodulus/demeteorizer#160]
hi all,

i try to run the converted app, but in the step npm install throut an error:

npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
/
> fibers@1.0.5 install /Users/Cuc4rach4/Vita-FX/converted/bundle/programs/server/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp WARN EACCES user "Cuc4rach4" does not have permission to access the dev dir "/var/root/.node-gyp/4.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Users/Cuc4rach4/Vita-FX/converted/bundle/programs/server/node_modules/fibers/.node-gyp"

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/Cuc4rach4/Vita-FX/converted/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Cuc4rach4/Vita-FX/converted/bundle/programs/server/npm-debug.log

[npm-debug.txt](https://github.com/onmodulus/demeteorizer/files/81097/npm-debug.txt)

i attached the debug log.

thanks.

**Comment by fiveisprime** [comment]
Hi! Meteor has a pretty strict dependency on the version of node due to some
compiled modules that won't work with later versions (for example, fibers).
You'll need to switch to node version 0.10.40 when running `npm install`.
