### ISSUE TITLE
-D option is not working

### ISSUE THREAD

**Issue by johnreitano** [onmodulus/demeteorizer#161]
I've got a bug that shows up when I deploy using demeteorizer (on Modulus.io), but it's really hard to debug it in the browser console because the javascript code is minified.

Is there a way to turn off code minification so I can debug the code?

I tried deploying with `modulus deploy --meteor-debug` and also `modulus deploy --D` and I also changed NODE_ENV to "development", but am still getting the same problem.

**Comment by jackboberg** [comment]
I just tried to recreate using `modulus-cli@5.0.1` and was able to get non-minified project deployed using

`modulus deploy -D`

What version of the CLI are you using?

**Comment by johnreitano** [comment]
Hi Jack,

Sorry! Talked to a modulus rep yesterday on IRC. This issue was not caused
by demeteorizer…I had a package that was crashing and preventing code from
being re-deployed, so that’s why I was still being the minified code.

-John

**Comment by jackboberg** [comment]
Glad you worked it out
