### ISSUE TITLE
Meteor 1.2.1 Deploy failed on Modulus  

### ISSUE THREAD

**Issue by vladstan** [onmodulus/demeteorizer#167]
Tried with both modulus 5.0.1 and modulus@4. Actually the provisioning and the deploying worked just fine, but the server is not starting and I got this error:

Unable to connect to any application instances. These are the logs from the server:
module.js:340
    throw err;
          ^
Error: Cannot find module '/mnt/app/build/bundle/programs/server/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node main.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/build/bundle/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./build/bundle/programs/server/package.json
Start script specified in package.json: node main.js
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/build/bundle/programs/server
> node main.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/mnt/app/build/bundle/programs/server/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node main.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/build/bundle/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./build/bundle/programs/server/package.json
Start script specified in package.json: node main.js
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/build/bundle/programs/server
> node main.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/mnt/app/build/bundle/programs/server/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node main.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/build/bundle/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./build/bundle/programs/server/package.json
Start script specified in package.json: node main.js
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/build/bundle/programs/server
> node main.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/mnt/app/build/bundle/programs/server/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node main.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/build/bundle/programs/server/npm-debug.log

The support team @modulus suggested to start this issue here. 

Thanks

**Comment by fiveisprime** [comment]
What's the *.onmodulus.net URL for your project?

**Comment by vladstan** [comment]
together-by-startupkit-56117.onmodulus.net

**Comment by fiveisprime** [comment]
The Meteor application in your project is nested within the `app` directory so
it's not being converted on deploy.

Try running `$ modulus deploy` from within the `app` directory.

I'm not sure what that project template is though so I may be giving some bad
advice. Deploying just `app` will get it up and running though.

**Comment by vladstan** [comment]
This is not working. I'm using Iron-router to create this folder structure.

Error] Error: Command failed: /bin/sh -c meteor --version
Problem! This project does not have a .meteor/release file. The file should
either contain the release of Meteor that you want to use, or the word 'none'
if you will only use the project with unreleased checkouts of Meteor. Please
edit the .meteor/release file in the project and change it to a valid Meteor
release or 'none'.

**Comment by vladstan** [comment]
Problem solved. Thank you.

**Comment by dkrish** [comment]
@vladstan how did you fix this error? i'm running into the exact same thing deploying a Meteor app to modulus

**Comment by vladstan** [comment]
@dkrish are u using iron router scaffolding ?

**Comment by dkrish** [comment]
no, but i did find out what the error was (involved a password setting on
MongoDB). Thanks for the response, though!

On Wed, Feb 24, 2016 at 4:08 AM Vlad Stan <notifications@github.com> wrote:

> @dkrish <https://github.com/dkrish> are u using iron router scaffolding ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onmodulus/demeteorizer/issues/167#issuecomment-188223293>
> .
>
-- 
Dexter Krishnan
CEO, DK Innovations
www.dkla.net

**Comment by iamnathanwindsor** [comment]
How was this error fixed? I'm getting something similar?

I am using iron router.

http://projectpinnacle-88747.onmodulus.net/


Thank you for your help~

Now using node v0.10.41 (npm v3.10.6)
Found package.json: ./bundle/programs/server/package.json
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/bundle/programs/server
> node ../../main


assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/mnt/app/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.41/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/bundle/programs/server/npm-debug.log

**Comment by theworkflow** [comment]
@iamnathanwindsor Your project is using `meteor@1.4.1`, not `meteor@1.2.1`. Also, from your error, it looks like you need `node@4`. When you deploy you need to specify the node version you want to use.

```
$ modulus deploy -p <projectName> --node-version 4
```

**Comment by iamnathanwindsor** [comment]
Thank you @theworkflow for your quick answer over a weekend! 

Do you want me to use meteor 1.4.1 or 1.2.1?

THANK YOU FOR YOUR HELP~ When I fix this bug, I will repost my success here for other people, and then rave about Meteor/Modulus. It's super intuitive for Dapps/apps.

**Comment by theworkflow** [comment]
@iamnathanwindsor Those errors are just fields in the `package.json` that aren't defined. You can continue to use `meteor@1.4`. You just need to specify the `--node-version` flag when deploying from the CLI since your app uses `node@4` features.
