### ISSUE TITLE
Meteor application deployment fails as it is not adding all packages during deployment

### ISSUE THREAD

**Issue by mubeenkhan44** [onmodulus/demeteorizer#169]
I have a successful Deployment before on Modulus But now it fails as it is not adding all packages.It stoped on underscore@1.5.2 . I have just added fiber and npm webshot. It is working fine locally. 

Deployment Screen shows:
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /programs/server/package.json
Installing node 0.10.33
Installing npm 3.7.3
Installing packages from /programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.1 install /mnt/input/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
meteor-dev-bundle@0.0.0 /mnt/input/programs/server
├── fibers@1.0.1 
├── semver@4.1.0 
├─┬ source-map-support@0.2.8 
│ └─┬ source-map@0.1.32 
│   └── amdefine@0.1.0 
└── underscore@1.5.2 
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
v0.10.33
deploy -> v0.10.33
Uploading completed build.

Modulus Log:

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main
/mnt/app/programs/server/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Can't find npm module 'string'. Did you forget to call 'Npm.depends' in package.js within the 'aldeed_simple-schema' package?
    at Object.Npm.require (/mnt/app/programs/server/boot.js:147:17)
    at expectedType (packages/aldeed:simple-schema/simple-schema.js:8:1)
    at /mnt/app/programs/server/packages/aldeed_simple-schema.js:2001:4
    at /mnt/app/programs/server/packages/aldeed_simple-schema.js:2961:3
    at /mnt/app/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /mnt/app/programs/server/boot.js:116:5

Modulus URL shows: Unable to connect to any application instances.

**Comment by sjmcdowall** [comment]
I am not sure this is a demeteorizer issue is it?  Seems more like a modulus deployment problem?  Also -- this is certainly NOT your issue, but if you are using Meteor 1.2 as the base framework, the proper version of node is 0.10.40 not 0.10.33 as you seem to be using?  

I've never had luck changing the _underscore version from the default one in Meteor -- I wish they would update the core packages to more current ones ..

**Comment by mubeenkhan44** [comment]
i think modulus is not supporting METEOR@1.0.3.2 release (Node 0.10.33v). I just run meteor update command and it updated METEOR to 1.2.1. Now my Node version is 0.10.40 and it works fine with modulus deployment.
Thanks for your help @sjmcdowall

**Comment by harlanj** [comment]
@mubeenkhan44 Sorry for the late response on this. There have been updates to our build image on respecting the `package.json` that's in the root directory of your Meteor application. If you're still experiencing issues please re-open and let us know what errors you're noticing.
