### ISSUE TITLE
Meteor/Modulus Deploy Hanging

### ISSUE THREAD

**Issue by robbiereynolds** [onmodulus/demeteorizer#170]
I'm able to successfully login into Modulus from CLI and cd to my local project directory. Run modulus deploy ENTER
Meteor project detected...
Downloading npm-bcrypt@0.7.8_2... \
The process just continues to run and nothing happens after 15+ minutes.

Via Modulus support attempted:

Run demeteorize, zip bundle and upload via web console. Application log:

Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main

/mnt/app/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: /mnt/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/mnt/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/mnt/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log
Now using node v0.10.40
Found package.json: ./programs/server/package.json
Start script specified in package.json: node ../../main
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main

**Comment by sjmcdowall** [comment]
Hmm... did you run demeteorizer and do a "npm install" on the demeteorized bundle before you zipped it? Not sure of the sequence you did.  I am wondering if the arch platform you ran demeteorizer on is the same as the deployment one ?  Certainly if you run "npm install" it needs to be the same because a lot of components are compiled (hopefully pre-compiled) .. but I'm a bit out of my league here ..

**Comment by robbiereynolds** [comment]
Yes, I ran npm install after demeteorize in the the .demeteorized/bundle/programs/server and then zipped. Uploaded to Modulus via web console.

**Comment by sjmcdowall** [comment]
Ah -- so what platform did you run demeteorizer on?  And -- do you happen to know what Modulus deploys on?  My gut feeling is there is a discrepancy between the 2 that is causing this .. Mac vs Linux say...

**Comment by robbiereynolds** [comment]
I'm actually using a Windows 10 machine for development and deploying on Modulus (which I don't really know much about the architecture). I should also mention, I'm very much new to Meteor and the deployment process.

**Comment by sjmcdowall** [comment]
Ah ha! Well that would explain it for sure.  Basically, running demeteorizer is fine -- no problems there.  But when you do a "npm install" it basically grabs everything FOR THE CURRENT PLATFORM needed.  In this case, it's grabbing all Windows X64 bits and pieces -- and a little known fact is that a bunch of critical npm modules are actually compiled C++ components for pure raw speed.  Meteor uses at least 3 of these I know of (and maybe more).  This is why when you copy the files (after npm install) and put them on Modulus it doesn't work -- you grabbed Windows "binaries" and are trying to run them on Linux (I am 99% sure Modulus is running some Linux variant).  

Have you tried to follow the steps as outlined here

[http://meteortips.com/deployment-tutorial/modulus/]

You may also find that running these type of commands from a "shell" like environment easier and less error prone.  I use git-bash on Windows to emulate a Mac/Linux command line.  However, you shouldn't need that per se I don't think as the modulus npm command will PROBABLY work on a shell command line.

**Comment by robbiereynolds** [comment]
I elected to install Ubuntu and have a dual boot machine. I've got everything up and running just perfect. Meteor, Node.js, NPM, deploy to modulus, android package, etc.
