### ISSUE TITLE
Meteor app deploys successfully, but doesn't show up at IP address

### ISSUE THREAD

**Issue by shaynadc** [onmodulus/demeteorizer#174]
After spending 3 days getting everything set up with demeteorizer on Windows Server 2012, I've finally gotten everything to build and deploy successfully. `node main.js` runs (although gives zero output), but my problem here is that nothing is showing up at my IP address.

I've set the `ROOT_URL=http://xx.xxx.xxx.xxx`, but when I navigate to that IP online, I get a "site can't be reached, IP:xx.xxx.xxx.xxx took too long to respond" error.

Can you give me any insight?

AWS EC2 running Windows Server 2012,
Meteor v1.2.1
Node v0.10.40
npm v1.4.28
Python v2.7.11
Demeteorizer v3.0.1
Mongo Server 3.2

Thanks.

**Comment by sjmcdowall** [comment]
meteor apps always start up with some messages on output .  Not seeing anything is suspicious.  When you run locally (assuming you can/do and did to create the deploy package) -- it should have said something.  

Also - how are you running Mongod ??  I am not familiar with AWS and how to deploy a multi-part app like Mongo / node etc. to that environment so not much help alas.  

But confirm it DOES run locally fine ??  

And -- how exactly did you get "everything to build and deploy" successfully?  What steps?

**Comment by harlanj** [comment]
@shaynadc is this still an issue for you?

**Comment by shaynadc** [comment]
@harlanj it's working now! Even though 8080 is default, I still had to explicitly set it with `SET_PORT=8080`. I had simply not considered it because it was supposed to be default (in my mind). Meteor didn't ever run a single output.

I ended up abandoning demeteorize though and just using the meteor build function. Very good tutorial here: https://forums.meteor.com/t/one-deployment-method-for-a-meteor-application-on-windows/13928. Tip: you need `msvs_version=2013` when you run npm install

Mongo set up was also onerous, but this tutorial got it set up easily as a service. I've gotten Meteor running well on several different windows 2012 servers, so I feel pretty comfortable with it now. Shoot me a message if you get stuck!

**Comment by harlanj** [comment]
@shaynadc thanks for the feedback! I'm going to close this issue. Please feel free to open it again if you ever decide to use `demeteorizer` again and are still experiencing the issues you've listed above.
