### ISSUE TITLE
Meteor application deployment errors

### ISSUE THREAD

**Issue by fvpDev** [onmodulus/demeteorizer#176]
https://github.com/onmodulus/modulus-cli/issues/100

Hi you guys; I keep getting the following error log upon `meteor deploy` however it tells me that my app is "running" at "url" but all I get is "Unable to connect to any application instances".
Sorry for such a long log, but I'm not well-versed enough in error logs to go through and separate all of the different errors that have popped up.

Local windows machine npm package versions
`node --version` = `v5.5.0`
`modulus --version` = `5.0.1`
`demeteorizer --version` = `3.0.1`

```
I:\OneDrive\_fvpDev\Resources\_meteor\testGrounds\_for4RM>modulus deploy
Welcome to Modulus
You are logged in as fvpCo
Please choose which project to use:
  1)  00 SRS - Website   Node.js
  2)  01 CCH - Website   Node.js
  3)  02 JNYP - Website  Node.js
  4)  04 RM - Website    Node.js
[?] project 4
Selecting 04 RM - Website

Meteor project detected...

WARNING: The output directory is under your source tree.

Compressing project...
28.5 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Node.js runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server/package.json
Installing node 0.10.40
Installing npm 3.8.3
Installing packages from /I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.5 install /mnt/input/I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server/node_modules/fibers
> node ./build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/mnt/input/I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
../src/coroutine.cc:64:53: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
  for (pthread_key_t ii = coro_thread_key - 1; ii >= 0; --ii) {
                                                     ^
../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tls == thread_id) {
   ^
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/mnt/input/I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server/node_modules/fibers/build'
Installed in `/mnt/input/I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
meteor-dev-bundle@0.0.0 /mnt/input/I/OneDrive/_fvpDev/Resources/_meteor/testGrounds/_for4RM/.demeteorized/bundle/programs/server
├── ansi-regex@0.2.1
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── fibers@1.0.5
├── has-ansi@0.1.0
├─┬ meteor-promise@0.5.0
│ └─┬ promise@7.0.4
│   └── asap@2.0.3
├── semver@4.1.0
├─┬ source-map-support@0.3.2
│ └─┬ source-map@0.1.32
│   └── amdefine@1.0.0
├── strip-ansi@0.3.0
├── supports-color@0.2.0
├── type-of@2.0.1
└── underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
v0.10.40
deploy -> v0.10.40
Uploading completed build.
Provisioning and deploying bundle to servos...

[✓] 04 RM - Website running at 04-rm-website-60835.onmodulus.net
```

**Comment by sjmcdowall** [comment]
This doesn't appear to be a demeteorizer issue -- but rather a modulus one?  Perhaps asking on their support site / forums would help.  However, any time I see Fibers trying to be compiled that throws red flags for me -- unless you are on Windows you shouldn't need to ever compile fibers.. <shrug>

**Comment by fvpDev** [comment]
Lol I am on windows..

**Comment by sjmcdowall** [comment]
Since I am not a modulus user -- how exactly (step by step) do you deploy a meteor app to modulus?  Where / when in the process do you use demeteorizer?  And yes, Modulus is a Linux X64 back end -- so maybe some of the issue is Windows -> Linux. Fibers is compiled so that makes it more complex.

**Comment by fvpDev** [comment]
If you look at the logs above you'll see that the `.meteor` folder gets compressed and uploaded to Modulus first, and then demeteorizer starts building on the server. So the issue doesn't have anything to do with what platform I am using as far as I can tell.

Screenshot clip from my.modulus.io:
![image](https://cloud.githubusercontent.com/assets/10249425/14116500/0a3bd91e-f5ae-11e5-98b6-3a98cfd28e73.png)

**Comment by harlanj** [comment]
The Modulus CLI tool demeteorizes your Meteor application before sending it to the build servers. `demeteorizer` is a [dependency](https://github.com/onmodulus/modulus-cli/blob/master/package.json#L38) of the `modulus-cli`. After the CLI demeteorizes your application, the `.demeteorized` directory is zipped up and sent to the build servers and then all of the modules defined in the `package.json`, located in the `.demeteorized/bundle/programs/server` directory, are installed. This is where the start script, node version, and main file are defined as well. 

Hopefully that explains how to deploy a Meteor app to Modulus. 

We're using Ubuntu servers for your servo. You can view more information on your servo and what's installed [here](https://github.com/onmodulus/docker-run-node). It's just a Docker container that runs your app basically. 

So your application did successfully deploy. As for your project @fvpDev you may want to check into your logs to see what errors you're getting. We just pipe your logs from stdout so that you can still access them.

Does this clear up any confusion?

**Comment by fvpDev** [comment]
Ok, thnx for clearing that up.

I had to downgrade back to v4.0.2 modulus cli for it to work. I will upgrade back to the latest version and do `modulus deploy` and you will be able to see the `Unable to connect to any application instances`

**Comment by fvpDev** [comment]
Yup...I'm getting the same error log as the initial post in this issue thread and:
http://04-rm-website-60835.onmodulus.net/

**Comment by fvpDev** [comment]
To bad I can't include `.demeteorized/bundle/programs/server/npm-debug.log` in a support request...

![image](https://cloud.githubusercontent.com/assets/10249425/14118170/35ac60a2-f5b6-11e5-8cdf-450417713183.png)

**Comment by harlanj** [comment]
In regards to you installing the Modulus CLI, that error is from one of the CLI's dependencies. Demeteorizer uses [`win-span@2.0.0`](https://github.com/onmodulus/demeteorizer/blob/master/package.json#L28) and I'm not sure about `graceful-fs` off the top of my head.

I believe there was/is a problem with the latest version of the CLI and deploying Meteor apps. It has a problem with compiled npm modules. Fibers may be breaking builds. We haven't been able to do much testing with the new version of Meteor.

**Comment by fvpDev** [comment]
Same thing was happening with Meteor 1.2.1 with a different compiled npm module. Do you know which is the latest version I can use for this not to happen, 4.0.2?

**Comment by harlanj** [comment]
For the CLI, you can use `modulus-cli@4.x` if you're having compiling issues. This would be the case here. If you're not getting a compile error, then you can use `modulus-cli@5.x`

**Comment by fvpDev** [comment]
Easier / works better to use Meteor Environment for a meteor project rather than Node.JS.
#177
