### ISSUE TITLE
"npm start" don't work on windows 10.

### ISSUE THREAD

**Issue by thearabbit** [onmodulus/demeteorizer#200]
`npm start` don't work on windows 10
```js
> Set MONGO_URL=mongodb://localhost:27017/test
> ROOT_URL=http://localhost:8080
> npm start
```
But don't work
```js
C:\Users\Theara\Desktop\meteor_app\testing\.demeteorized\bundle\programs\server>SET ROOT_URL=http://localhost:8080

C:\Users\Theara\Desktop\meteor_app\testing\.demeteorized\bundle\programs\server>npm start

> meteor-dev-bundle@0.0.0 start C:\Users\Theara\Desktop\meteor_app\testing\.demeteorized\bundle\programs\server
> node ../../main
```
(I can't run it with one line like `Ubuntu or Mac`)

**Comment by Xurma2** [comment]
@thearabbit the same problem. You solved?

**Comment by thearabbit** [comment]
don't solved yet.

**Comment by sjmcdowall** [comment]
What are the error messages and full output being returned?  What version of Meteor is this? What version of demeteorizer?  How was the demeoteorizer command run (all options) .. Hard to debug with the small amount of information here

**Comment by harlanj** [comment]
@thearabbit @Xurma2 apologies for the late response to your issue.

1) Are you still having this issue?
2) What version of `demeteorizer` are you using?
3) What is your full `demeteorizer` command and output?
4) What version of `node` and `npm`?
5) Any exit codes when trying to set `MONGO_URL` and `ROOT_URL` with `npm start`?
6) I also notice you're not setting `ROOT_URL`. It doesn't error out when you don't set that?

@sjmcdowall Thanks for the feedback! I totally give you credit for the points I made (as if we can't see that you said them first 😄)

**Comment by harlanj** [comment]
@thearabbit just checking back to see if you're still having this problem. If not, I can close the issue.

**Comment by harlanj** [comment]
@thearabbit if you're still experiencing this just reopen the issue with some details and we can start digging for you! 😄
