### ISSUE TITLE
Demeteorization fails due to missing isopack metadata files

### ISSUE THREAD

**Issue by azcn2503** [onmodulus/demeteorizer#215]
When demeteorizing my application, I get the following error:

	build	09-Aug-2016 13:18:59	> hub@0.1.0-proto build:demeteorize D:\Builds\PROD-HUB-JOB1
	build	09-Aug-2016 13:18:59	> demeteorizer
	build	09-Aug-2016 13:18:59	
	build	09-Aug-2016 13:19:00	Demeteorizing application...
	error	09-Aug-2016 13:22:40	C:\Users\BambooService\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
	error	09-Aug-2016 13:22:40	      throw error;
	error	09-Aug-2016 13:22:40	      ^
	error	09-Aug-2016 13:22:40	
	error	09-Aug-2016 13:22:40	Error: No metadata files found for isopack at: /C/Users/BambooService/AppData/Local/.meteor/packages/stolinski_stylus-multi/1.4.3
	error	09-Aug-2016 13:22:40	    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
	error	09-Aug-2016 13:22:40	    at C:\tools\packaging\tropohouse.js:520:19
	error	09-Aug-2016 13:22:40	    at Array.forEach (native)
	error	09-Aug-2016 13:22:40	    at Function._.each._.forEach (C:\Users\BambooService\node_modules\underscore\underscore.js:79:11)
	error	09-Aug-2016 13:22:40	    at C:\tools\packaging\tropohouse.js:519:11
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:359:18
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:352:34
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:350:23
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
	error	09-Aug-2016 13:22:40	    at Object.download (C:\tools\packaging\tropohouse.js:454:20)
	error	09-Aug-2016 13:22:40	    at C:\tools\packaging\tropohouse.js:598:22
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:359:18
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:352:34
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:350:23
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
	error	09-Aug-2016 13:22:40	    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:595:20)
	error	09-Aug-2016 13:22:40	    at C:\tools\project-context.js:748:25
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:359:18
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:352:34
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:350:23
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
	error	09-Aug-2016 13:22:40	    at C:\tools\project-context.js:747:20
	error	09-Aug-2016 13:22:40	    at C:\tools\packaging\catalog\catalog.js:100:5
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:271:13
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:264:29
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:262:18
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:253:23
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
	error	09-Aug-2016 13:22:40	    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
	error	09-Aug-2016 13:22:40	    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:746:13)
	error	09-Aug-2016 13:22:40	    at C:\tools\project-context.js:268:9
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:359:18
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:352:34
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:350:23
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
	error	09-Aug-2016 13:22:40	    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
	error	09-Aug-2016 13:22:40	    at C:\tools\project-context.js:250:12
	error	09-Aug-2016 13:22:40	    at Function.run (C:\tools\tool-env\profile.js:489:12)
	error	09-Aug-2016 13:22:40	    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
	error	09-Aug-2016 13:22:40	    at C:\tools\cli\commands.js:843:20
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:271:13
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:264:29
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:262:18
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at C:\tools\utils\buildmessage.js:253:23
	error	09-Aug-2016 13:22:40	    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
	error	09-Aug-2016 13:22:40	    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
	error	09-Aug-2016 13:22:40	    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
	error	09-Aug-2016 13:22:40	    at buildCommand (C:\tools\cli\commands.js:842:8)
	error	09-Aug-2016 13:22:40	    at Command.func (C:\tools\cli\commands.js:796:12)
	error	09-Aug-2016 13:22:40	    at C:\tools\cli\main.js:1410:23
	error	09-Aug-2016 13:22:40	Conversion failed.

How can I resolve this issue? Many thanks.

**Comment by sjmcdowall** [comment]
Couple of questions that may help (or may not!) -- 

-- What version of node is on your command line   (node --version)
-- What version of demeteorizer? 

Demeteorizer, at it's heart, uses the meteor build command line to do a lot of the preliminary work .. what happens if you try to 'meteor build' the same application?

**Comment by azcn2503** [comment]
Hey there,

My Node version is at v6.3.1 (x86) and demeteorizer is at v4.0.0.

I seem to only be receiving this error on my Windows machine. I am able to run the demeteorizer command on the same repository on my Mac without any issues.

I just tried the `meteor build` command and I got the same error message. I am able to run it on the Mac without any problems but the Windows machine is giving me the error.

**Comment by sjmcdowall** [comment]
Unfortunately you may have to ping the Meteor gang on this since if a meteor build doesn't work on Windows -- demeteorizer isn't going to either (obviously).  Alas, anything Fibers related and Windows is a mess at the best of times ..

Oh and they'll probably want to know which Windows platform too .. 

Once you can get a plain meteor build to work on your Windows platform, demeteorizer should work then too ..

**Comment by azcn2503** [comment]
Thanks @sjmcdowall I'll ask on the Meteor forums.
