### ISSUE TITLE
page not loading

### ISSUE THREAD

**Issue by doodiosie** [onmodulus/demeteorizer#221]
I followed the steps on my own meteor app and I found that although the node server was running, when I visited localhost:8080 I got "ERR_EMPTY_RESPONSE".  So I tried using the example commands you have for the leaderboard and copy and pasted each of them exactly (except the meteor create one which doesn't work anymore) and I have the same problem.  Is this a bug or am I just doing something wrong.

I'm using mac OSX el capitan and the latest versions of meteor, mongo and demeteorizer at time of posting

**Comment by harlanj** [comment]
@doodiosie can you post the commands you ran and the output of those commands? What version of Meteor are you using? What version of Meteor did the `leaderboard` app use?

**Comment by doodiosie** [comment]
Sorry to be irritating, I still don't know why but it started working once I ran it on port 8000 instead of 8080.  I had checked to ensure that I didn't already have something on port 8080 but maybe I did and that is why it didn't work.  Thanks for the help though :)

**Comment by harlanj** [comment]
No problem! Going to close this issue.

**Comment by sjmcdowall** [comment]
Port 8080 is probably the 2nd most popular port to be used for Web apps (after 80) .. and just before 3000 :)  So it's not totally surprising it may have been in use by "something".  :)
