### ISSUE TITLE
SSL on demeteorized application 

### ISSUE THREAD

**Issue by yrvlucero** [onmodulus/demeteorizer#240]
I am deploying an app to Windows 2008 r2. How can I add ssl support to my application?

**Comment by sjmcdowall** [comment]
The same way you'd do it on any other platform -- in general maybe this guide will help?  Every situation is specific .. but the end result of a demeteorized app is just a standard node app in the end ... 

http://joshowens.me/ssl-and-meteor-js/

**Comment by fiveisprime** [comment]
Closing this since it's out of scope of demeteorizer. 👍
