### ISSUE TITLE
Replace server/npm/node_modules folder with package.json

### ISSUE THREAD

**Issue by Kostanos** [onmodulus/demeteorizer#241]
My current tar.gz file is more than 30Mb, which makes me wait a lot to upload it on server.

Is there any way to remove `server/npm/node_modules` folder and re-create it again on server, without installing meteor on it?

In other words, I would like to putt all dependencies on that folder inside `package.json` and re-create it with `npm install` on server.

**Comment by vladejs** [comment]
You can upload just a zipped version of your source code. It worked for me a while (meteor 1.2), but with recent meteor versions, they still uses node 0.10.41, which gives you errors. 

This is reported in #241
