### ISSUE TITLE
Modulus still uses nodejs 0.10.x to deploy an app

### ISSUE THREAD

**Issue by vladejs** [onmodulus/demeteorizer#243]
If I upload my source code to modulus, it says is using node 4.4.7 and latest npm. 

But that's only to install my npm deps. After the app is demeteorized, it actually _run_ it with node v0.10.x.

I can only change that behaviour if I demeteorize locally and change node version on package.json file.

As a result, all my apps are getting an Assertion error. 
`undefined == function`.

To reproduce the issue just do this:
1. `meteor create itwillfail`
2. Zip the itwillfail content (not the folder itself)
3. Upload the zip to modulus via web interface

I use v1.4.1 but it happens in every meteor version you use.

**Comment by jackboberg** [comment]
You can use [`--node-version`](https://github.com/onmodulus/demeteorizer/blob/master/bin/demeteorizer#L31-L33) to specify what you want written to the `package.json`. This option is also available to the `modulus` CLI.

**Comment by vladejs** [comment]
How I' am  suppose to specify `--node-version` when I upload my source code to modulus via web interface?

**Comment by theworkflow** [comment]
You can manually update the `package.json` in `demeteorized/bundle/programs/server/packge.json`

**Comment by vladejs** [comment]
Lol. @theworkflow , the idea is to upload only my source code and let modulus demeteorize de project, because is a meteor project, not a nodejs one.

**Comment by jackboberg** [comment]
@vladejs You are right, and unmodified source zip will default to whatever is in [`boot.js`](https://github.com/onmodulus/demeteorizer/blob/master/lib/find-node-version.js#L26-L34). `demeteorizer` could maybe pull from a root `package.json` engines property if specified..

**Comment by jackboberg** [comment]
@vladejs sorry for the confusion, I think the issue is differentiating between what `demeteorizer` does (or should do)...and what `modulus` does (or should do).

**Comment by vladejs** [comment]
Modulus always uses `demeteorizer`

**Comment by jackboberg** [comment]
maybe we can include copying over the root `package.json` engines property as a part of onmodulus/demeteorizer#228

**Comment by vladejs** [comment]
Sure, that would be a fix

**Comment by vladejs** [comment]
Hello @jackboberg , noticed #228 and #250 didn't solved my problem with Modulus, I have updated my `package.json` with `engines` property to use node v4.5.0 and when deploying to Modulus, I got the same node version no matter what.

This is what I get every single time I do `modulus deploy`:

> Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v4.4.7 (npm v3.10.5)
Installing root package.json dependencies.

**Comment by vladejs** [comment]
PLEASE FIX THIS. I can't even deploy using CODESHIP. On the above output it says 
>Now using node v4.4.7 (npm v3.10.5)

**BUT**, when deploy finishes it says:
```
Now using node v0.10.41 (npm v1.4.29)
deploy -> v0.10.41
Installing packages from /mnt/output/bundle/programs/server/package.json
...
```
## This is **critical**.
The only way I can now set a working project on Modulus is by:
1. Demeteorizing locally
2. Changing `engines` property on `/program/server/package.json` to use node 4.5.0
3. Compress the **HUGE** bundle and upload to Modulus via web interface

**Comment by jackboberg** [comment]
@vladejs I am taking a look at your project now. In our tests here, `demeteorizer` definitely supports setting the version via root `package.json`, and as you can see [here](https://github.com/onmodulus/docker-build-meteor/blob/master/bootstrap.sh#L13) Modulus updated the build image to use the new features from `demeteorizer`..

**Comment by jackboberg** [comment]
*Update*: able to reproduce, digging deeper. Thanks @vladejs for bringing this back to my attention.

**Comment by jackboberg** [comment]
@vladejs we rebuilt the docker images, updated the registry, and it seems to be resolved now:

```
Demeteorization complete.
Now using node v4.5.0 (npm v2.15.9)
deploy -> v4.5.0 *
```

Please try again and let me know if you still see the issue.

**Comment by vladejs** [comment]
Well @jackboberg , you **almost** got it.
CodeShip is giving me a green flag, **BUT**, my app still fails.

## Why?

See the output on your own comment:
> Demeteorization complete.
Now using node v4.5.0 (npm v2.15.9)
deploy -> v4.5.0 *

It says **NPM version 2.15.9** was used, so you can guess, NodeJS > 4 don't work well with NPM < 3.
As a result, my meteor app is not getting right my *npm dependencies*. Please fix that in a way demeteorizer correctly reads the `npm` property on my `package.json`:

```
"engines": {
  "node": "4.4.7",
  "npm": "latest"
}
```

**Comment by jackboberg** [comment]
I saw that, and opened an issue here earlier: onmodulus/docker-build-meteor/issues/35

I think we should move this discussion there, since it's no longer an issue with `demeteorizer`

**Comment by vladejs** [comment]
Problem solved. CodeShip is now giving me a green flag.
