### ISSUE TITLE
meteor with dummy mongo URL doesn't work

### ISSUE THREAD

**Issue by julian-rare** [onmodulus/demeteorizer#261]
I'm using meteor with a dummy URL because I'm not using mongo, wen I do **meteor run** works as expected, I don't have any collection definitions in my code or any other reference to mongo, so my code works as expected, but wen I run the demeteorizer version, I get an error because it's trying to connect to a dummy mongo db.

**Comment by fiveisprime** [comment]
This must be something with the way Meteor launches and runs the MongoDB process
along with the application. Something that a converted application can't manage
(this is out of scope).

I did find [this question on SO](http://stackoverflow.com/questions/18545905/meteor-without-mongo)
that claims you can remove the mongo package by running a couple of commands. I
would expect this to also work for a converted app.

```shell
$ meteor remove meteor-platform
$ meteor add  meteor webapp logging tracker session ddp blaze spacebars templating check underscore jquery random ejson templating check underscore jquery random ejson
```

Try removing the platform then adding back everything but mongo and re-running
demeteorizer.

**Comment by julian-rare** [comment]
Thank you @fiveisprime, I did remove the mongo package, but another one from atmosphere brought it back, so looks like is not demeteorizer problem, you can close this.
