### ISSUE TITLE
Meteor app deployed on azure, throw an error and doesn't show up

### ISSUE THREAD

**Issue by nwabdou85** [onmodulus/demeteorizer#264]
Hi,
My app deployed with demeteorizer on Azure successfully but doesn't show up at Url http://www.elkoufa.com/ neither this one http://elkoufa.azurewebsites.net/ and throwing an internal server error; 

![deme](https://cloud.githubusercontent.com/assets/6404998/23065543/60313b44-f516-11e6-88d8-e816f1f296ab.jpg)

But it run locally in linux and windows, it run also on herokuapp https://elkoufa.herokuapp.com/

Thank's

**Comment by fiveisprime** [comment]
Some questions about your env

* Are you running in app service?
* Is the app running in a Windows or Linux environment?
* Can you paste in your deploy logs from the Azure portal?

**Comment by fiveisprime** [comment]
Seems related to #265 

Read my suggestion there and see if that helps.

**Comment by nwabdou85** [comment]
@fiveisprime  yeah yeah it's related, Thank's
