### ISSUE TITLE
Adding CDN url in app.html for CSS & JS

### ISSUE THREAD

**Issue by insidesmart** [onmodulus/demeteorizer#36]
Hi,

Thanks for demeteorizer. It is very useful in the meteor deployment.

In the demeteorizer script, can you add the following feature. This helps everyone to have a better initial load experience for meteor projects.

```
demeteorizer -n 0.10.21 -cdn https://xxxx.cloudfront.net (or any cdn url)

or with an environment variable called CDN_URL stored in the project. This can be useful for modulus or any other PAAS deployments to pick it before running demeteorizer.

```
This will be converted in app.html produced by demeteorizer as following
```
<link rel="stylesheet" href="https://xxxx.cloudfront.net/8bdd2467e6f7668b49ed65b2ada56485fa17dbdf.css">

 <script type="text/javascript" src="https://xxxx.cloudfront.net/473509c044261c4d9fde1939f4d51a1bd19aa7b2.js"></script>

```

Obviously, you can do these steps using a bash script or manually editing them. Doing this with demeteorizer will be very useful.

Let me know if it is possible or if you have any other better ideas.

Thanks again

**Comment by JamesMGreene** [comment]
:+1:

**Comment by bradvogel** [comment]
Btw, here's a script I'm using as a workaround: https://gist.github.com/bradvogel/c2e1e6e26522216f6bdb
