### ISSUE TITLE
Package demeteorized meteor app with node-webkit?

### ISSUE THREAD

**Issue by praneybehl** [onmodulus/demeteorizer#63]
Meteor is pretty awesome and so is demeteorizer to help deploy meteor app anywhere. Even more more tempting is the ability to run a demeteorized app to node-webkit.

I have been trying to run a demeteorized meteor app on node-webkit but been running into issues.
Has someone tried doing it? Any success? An example will be really appreciated.

Thanks in advance

**Comment by iurimatias** [comment]
@praneybehl any success with this?

**Comment by praneybehl** [comment]
No sorry nothing yet, have you tried it, any success?

**Comment by sjmcdowall** [comment]
You may want to look at the Electrometeor project on git-hub.  It's a work in progress but I think it's what you want to do? https://github.com/sircharleswatson/Electrometeor

**Comment by harlanj** [comment]
@praneybehl sorry for the stale issue. What issues are you running into when trying to get your app up and running? If this is no longer an issue let us know so we can close this issue for you.
