### ISSUE TITLE
Demeteorization failed - deprecated command

### ISSUE THREAD

**Issue by ScOut3R** [onmodulus/demeteorizer#97]
Hi!

After upgrading Meteor to 1.0 I get this error when I try to demeteorize my app:

```
Determining Meteor version...
Meteor version: 1.0
Output folder exists, deleting...
Bundling Meteor App...
Demeteorization failed: This command has been deprecated in favor of 'meteor build', which allows you to
build for multiple platforms and outputs a directory instead of a single
tarball. See 'meteor help build' for more information.
```

I'm using 2.0.4.

**Comment by jscottsf** [comment]
Also having this problem via Modulus deployment. Any word on what's going on?

**Comment by tom2strobl** [comment]
+1 Demeteorizer is still not usable

**Comment by fiveisprime** [comment]
Please run the following:

```shell
$ meteor create --example leaderboard
$ cd leaderboard
$ demeteorizer
$ cd .demeteorized
```

You will see the same deprecation warning and still get the
`.demeteorized` directory (I promise that this is an issue deeper
down). The deprecation warning is only a warning and is not
what's causing the command to exit. There's something in your
Meteor project that's causing a real error which appended to the
deprecation warning on exit.

I can help get through the various errors that people are running into,
but I need to see the full errors so I can get to work on those.

:heart:

**Comment by amor520** [comment]
+1
